### ISSUE TITLE
transient dependencies and externals

### ISSUE THREAD

**Issue by rettgerst** [lostpebble/generate-package-json-webpack-plugin#10]
I am using this plugin in conjunction with webpack-node-externals and it seems that this setup has poor support for transient dependencies (aka, sub-dependenices).

I am building a distribution build of our serverside app which uses several private modules namespaced with '@apagoinc'. I want our private modules included in the bundle and everything publicly available from npm included in the generated package.json file. our private modules have their own dependenices, for example sharp (a native module which _cannot_ be included in the bundle) and bluebird (a normal js module which could be included in the bundle, although I'd prefer it not to be).

neither bluebird nor sharp are directly included in the source package.json and the webpack bundle code contains require statements for sharp and bluebird, however the generated package.json has no references to sharp or bluebird even though they are required.

**Comment by lukebellamy053** [comment]
I am also looking for this feature otherwise adding the dependencies to the webpack config seems to defeat the purpose

**Comment by lostpebble** [comment]
I've had similar issues before with transient dependencies and its something I would like to solve better with this library.

Unfortunately at the moment I have loads of other work keeping me busy, so if anyone would like to look at it it would be greatly appreciated - otherwise I might be able to get to it in the next few weeks.

I think the issue lies with figuring out how to get the correct version numbers of those transient dependencies, because they can't be sourced from your passed-in versions file. It would probably involve looking into the closest `node_modules` for whichever version is being used.

If we can get it right, its potentially actually a better way than how it works now, as we can automatically infer the versions instead of having to source them with a passed-in file.

**Comment by lostpebble** [comment]
Hi guys, please try out `1.1.1` - providing the option `useInstalledDependencies: true` - this will rather look to your `node_modules` directly for version numbers , and _should_ solve this issue of transient dependencies.
