### ISSUE TITLE
Allow to create directory if not exists

### ISSUE THREAD

**Issue by minkeshj** [lostpebble/generate-package-json-webpack-plugin#19]
Currently the directory where package.json needs to be placed if that does not exists then it throws following error
`Error: ENOENT: no such file or directory`. We should have a check if the directory does not exists then create it first then create package.json

**Comment by lostpebble** [comment]
Hi @minkeshj ,

Will need to look into that.

I was under the impression that webpack takes care of all that. Since all this plugin is doing is generating a `package.json` file, which is spat out into whatever destination folder you've set with your webpack config. It just creates an "asset" which will be available in the final output.

Can you track down exactly where that error is happening? Is it happening from inside this plugin? In that case, make sure that your `versionsPackageFilename` has been set correctly, as it could be a reading error as well.

**Comment by lostpebble** [comment]
Since I have never encountered this issue, and we have got no response about how it is happening- I'm closing this for now.
