### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by jreilly-lukava** [lostpebble/generate-package-json-webpack-plugin#30]
This appears happen because compilation.hooks.processAssets is undefined.

I really don't know much about webpack, but was using this package in my monorepo to generate a package json.  It worked fine when using Angular 11 with Webpack 4, but now it looks like it's having an issue maybe since Angular uses webpack 5?

**Comment by kraiz** [comment]
I wonder why this is happing as release 2.1.0 intended to add 'Webpack 5 support' :/

**Comment by jreilly-lukava** [comment]
I've created an [example repo](https://github.com/jreilly-lukava/example).  It's a fairly stock nx workspace with angular & nestjs.  I of course added a few things to do the custom webpack stuff to reproduce this issue.  Just install everything and then `pnpx nx build api`

**Comment by lostpebble** [comment]
I tried to fix it but I don't use Webpack 5 and I didn't manage to get it working correctly. I'd perhaps need someone who works with Webpack 5 to take a closer look.

**Comment by lostpebble** [comment]
I think there is some funny business happening here- because if you really were using Webpack 5, these methods would not be undefined. I think somehow parts of your compilation might still be using an older version of Webpack and its clashing in the plugin.

This is my best guess at the moment, because a lot of the things I've tried seem to indicate that it should work with Webpack 5- as there is a version check and the plugin uses documented Webpack 5 APIs.

For those having issues, please let us know more about your environment. Perhaps there will be some common things which will help to wattle it down (Angular compilation for example, etc.)

**Comment by MaGnaL** [comment]
I'm facing that issue too.

I think my case is most likely the same as the one of @jreilly-lukava. Nrwl/Nx workspace with Angular applications and NestJS backends. The plugin is used to generate a package.json for the NestJS backend. Angular applications include their dependencies directly into bundles. NestJS or NodeJS applications in general don't do that, that's why a package.json is needed for what this plugin comes in handy.

What I noticed is, that the Nrwl/Nx library which is needed to run NestJS backends, has a dependency to webpack 4. So I think @lostpebble is right, that even though the plugin detects the use of webpack 5 it is actually ran with webpack 4.

**Comment by MaGnaL** [comment]
When I force it to use the implementation for webpack 4 (`const isWebpack5 = false;`) it works as before.

**Comment by lostpebble** [comment]
Thanks @MaGnaL - appreciate you looking into it and confirming my suspicions.

So I take it most of you here (maybe all) are using the same kind of tooling then? I don't work with Angular, but it seems to be quite a substantial suite of things that run in that NX workspace with NestJS etc. I feel like somewhere in that pile of plugins there's a conflict going on.

An extra option to try next is to do a more "dynamic" check on which version of Webpack is _really_ being used during this part of the compilation. Its just strange because, `isWebpack5` gets its version directly from the imported `require("webpack")`. I just don't know what we can check for to make sure that the current execution is Webpack 4 or Webpack 5 without looking at the imported module version stuff- the documentation doesn't give many clues to this. Its strange as well because I tried moving the version check deeper into the code, but it still picks the wrong code to execute.

**Comment by MaGnaL** [comment]
Hey again,
I don't think that the code can be changed to detect the actually available version of webpack correctly or at least I couldn't find a way to do it.
What I did is added a new option to force the plugin to use one version or the other by overwriting the `isWebpack5` flag.

It's not nice or elegant but it works.

**Comment by lostpebble** [comment]
@MaGnaL - that could be the best solution then. Perhaps I should add an enum option in the plugin that can force the plugin to, currently, act as either `webpack4` or `webpack5`.

**Comment by MaGnaL** [comment]
I did the same thing and can provide a PR for that if you want.

**Comment by lostpebble** [comment]
No worries- I've just created the option and will be updating the version now, thanks though!

**Comment by lostpebble** [comment]
I've released 2.2.0 - https://github.com/lostpebble/generate-package-json-webpack-plugin/releases/tag/2.2.0

Please let me know if this works fine for you guys. Hopefully this puts and end to the Nx woes.

**Comment by MaGnaL** [comment]
Looks like it works 👍 thank you.

**Comment by lostpebble** [comment]
Cool, will close this for now. If anyone has any further issues feel free to comment and re-open.
