### ISSUE TITLE
Dependencies of an imported mono-repo library does not include it's dependencies

### ISSUE THREAD

**Issue by j** [lostpebble/generate-package-json-webpack-plugin#31]
I have this directory structure:

```
apps/
  graphql/

libs/
  auth/
  config/
```

If `graphql` imports `auth` which within `auth` (no package.json) requires 3rd party package `graphql-middleware`, `graphql-middleware` is not included in the final `package.json`.

I'm using Nx CLI.  So both `auth` and `config` are included in the final bundle, though I'm not bundling any external dependency within `auth` or `config`.  How can I go about including 3rd party dependencies?

**Comment by lostpebble** [comment]
Hi @j . Are you running on Webpack 5? And have you updated to the most recent version, `2.1.3` ? There were some issues with Webpack 5 that the newer version- I have personally just upgraded my projects to Webpack 5 and had the same problem only to realize I wasn't at the latest version, and after updating it did work for me.

Otherwise I fear you may be running into a similar issue that others have had with Nx CLI - where for some reason the Webpack version isn't stable (probably multiple versions installed internally) and it confuses the plugin. See: https://github.com/lostpebble/generate-package-json-webpack-plugin/issues/30

I've yet to find a solution for that.

**Comment by lostpebble** [comment]
Hi @j (btw, that's crazy you managed to get that username 😆 ),

I've released 2.2.0 - https://github.com/lostpebble/generate-package-json-webpack-plugin/releases/tag/2.2.0

Please let me know if this fixes your issue. Set the new `forceWebpackVersion` option to `webpack5`. Hopefully this puts and end to the Nx woes.
