### ISSUE TITLE
How to include shared folders?

### ISSUE THREAD

**Issue by TroyCoombs** [lostpebble/generate-package-json-webpack-plugin#8]
We have a mono-repo where we have code in one folder for a service, but some of the classes implement base classes in another shared folder.   What we're experiencing now is that the package.json is not including dependencies it needs in the shared folder.  How do I handle this?

**Comment by lostpebble** [comment]
Hi @TroyCoombs 

So, there is an option that I've included now but I haven't documented yet. It is in the release notes here though: https://github.com/lostpebble/generate-package-json-webpack-plugin/releases/tag/v0.4.0

In my case I was also working with a mono repo and needed this functionality. Basically you can link extra `package.json` files from which to pull dependency information from.

Does this suit your needs as well? Otherwise, if you can expand a bit more on what your project structure looks like it would help me understand what your needs are.

I'll be adding that stuff to the documentation soon, sorry about that.

**Comment by TroyCoombs** [comment]
Thanks for the reply @lostpebble. Not sure if it's the same but all our dependencies in the all apps are added to the main package.json of the mono-repo.  For example we have an app called 'AppA', ánother'called  'ÁppB, both apps add dependencies to the main package.json in the root of the mono-repo project.  We have a 3rd project in the mono-repo called 'common' which has shared code use by the other apps 'AppA' and  'AppB'.  So when I build 'AppA'the package.json should have dependencies that 'AppA' needs (which it does), but it should also have dependencies that from the common project for the code that AppA uses within it.  Mostly common project has base classes that classes in AppA Extends or implements.  Hope that makes sense.

**Comment by lostpebble** [comment]
Okay, I think I have some idea of what you're doing.

Basically this is my current configuration:

```
new GeneratePackageJsonPlugin(
        {
          name: "nodejs-frontend",
          version: "1.0.0",
          private: true,
          author: "lostpebble",
          scripts: {
            start: "cross-env-shell NODE_ENV=production node ./server.js"
          },
          dependencies: {
            "cross-env": "",
          },
          engines: {
            node: ">=9.8.0",
          },
        },
        join(__dirname, "/package.json"),
        {
          extraSourcePackageFilenames: [
            join(__dirname, "../../node_modules/@ggt/services/package.json"),
            join(__dirname, "../../node_modules/@vvs/core/package.json"),
            join(__dirname, "../../node_modules/@ggt/common-utils/package.json"),
            join(__dirname, "../../node_modules/@ggt/node-utils/package.json"),
            join(__dirname, "../../node_modules/@ggt/task-function-utils/package.json"),
          ],
        }
      )
```

As you can see I'm adding all the extra `package.json` files from my other projects. In your case, it sounds like you've put all your dependencies in the single root `package.json` instead of keeping them in the separate projects, `AppA`, `AppB` and `common`? In that case you might instead put this in there (depending how your directory structure looks):

```
join(__dirname, "../../package.json"),
```

I hope that works out for you. I could help much better if you can put together a small example repo I can look at and play around with.

You should also make sure that you are bundling your `common` project when you bundle `AppA` or `AppB`, you can do this by setting the common project in the `webpack-node-externals` plugins "whitelist" option. https://github.com/lostpebble/generate-package-json-webpack-plugin#important-note-on-externals

In my case I namespace all my modules so I can easier identify them with a regex, so I pass this array into that option:

```
whitelist: [/^@vvs/, /^@ggt/]
```

**Comment by lostpebble** [comment]
No response for a while, so gonna close this. Please let me know if you're still struggling with this - I think that the `extraSourcePackageFilenames` option along with white-listing internal project dependencies should do the trick.
